sudo: required
service:
  - docker

env:
  - CI=true

before_install:
  - docker build -t tchelidze/docker-tut-react -f Dockerfile.dev .

script:
  - docker run tchelidze/docker-tut-react npm run test